---

- name: enable nfs service
  sysrc:
    name: nfs_client_enable
    value: "YES"
  tags:
  - startup

- name: start nfs_client service
  service:
    name: nfsclient
    state: started
  tags:
  - startup
